apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: glasswallsolutions
spec:
  hosts:
  - glasswallsolutions.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: https-port-for-tls-origination
      protocol: HTTPS
    hosts:
    - glasswallsolutions.com
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-glasswallsolutions
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: glasswallsolutions
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 80
        tls:
          mode: ISTIO_MUTUAL
          sni: glasswallsolutions.com

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-glasswallsolutions-through-egress-gateway
spec:
  hosts:
  - glasswallsolutions.com
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: glasswallsolutions
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: glasswallsolutions.com
        port:
          number: 443
      weight: 100
      
---
  
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: originate-tls-for-edition-glasswallsolutions-com
spec:
  host: glasswallsolutions.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: SIMPLE
  