apiVersion: v1
data:
  BATCH_INTERVAL: "5000"
  BATCH_SIZE: "4"
  REQUEST_TYPES: |-
    [
        {
            "host": "nginx-service",
            "port": 80,
            "path": "/",
            "protocol": "http:",
            "method": "GET",
            "headers": {
                "Content-Type": "application/json"
            }
        },
        {
            "host": "nginx-service",
            "port": 80,
            "path": "/fake-path",
            "protocol": "http:",
            "method": "GET",
            "headers": {
                "Content-Type": "application/json"
            }
        }
    ]
kind: ConfigMap
metadata:
  name: loadgenerator-config
  namespace: default

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: default
  name: load-generator-deployment
spec:
  selector:
    matchLabels:
      app: load-generator
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: {HOST_IP}:5000/load-generator:latest
        envFrom:
        - configMapRef:
            name: loadgenerator-config
