apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: default
  name: nt-deployment
spec:
  selector:
    matchLabels:
      app: nt
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nt
    spec:
      containers:
      - name: nt
        image: praqma/network-multitool
