apiVersion: argoproj-io/v1alpha1
kind: Workflow
metadata:
  generateName: local-rebuild-
spec:
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: imageRegistry
        value: docker.io
      - name: endpoint
        value: play.min.io
      - name: accessKey
        value: Q3AM3UQ867SPQQA43P2F
      - name: secretKey
        value: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      - name: bucketName
        value: yarden-test

  templates:
    - name: entrypoint
      steps:
        - - name: list
            template: lister
        - - name: run
            template: runner
            arguments:
              parameters:
                - name: objectName
                  value: "{{item}}"
            withParam: "{{steps.list.outputs.result}}"

    - name: runner
      inputs:
        parameters:
          - name: objectName
      steps:
        - - name: download
            template: downloader
            arguments:
              parameters:
                - name: objectName
                  value: "{{inputs.parameters.objectName}}"
        - - name: process
            template: processor
            arguments:
              artifacts:
                - name: processor-input
                  from: "{{steps.download.outputs.artifacts.processor-input}}"
        - - name: convert-report-to-json
            template: convertor
            arguments:
              artifacts:
                - name: xml-report
                  from: "{{steps.process.outputs.artifacts.xml-report}}"

    - name: lister
      container:
        image: "{{workflow.parameters.imageRegistry}}/yardenshoham/local-rebuild-argo-lister"
        env:
          - name: ENDPOINT
            value: "{{workflow.parameters.endpoint}}"
          - name: ACCESS_KEY
            value: "{{workflow.parameters.accessKey}}"
          - name: SECRET_KEY
            value: "{{workflow.parameters.secretKey}}"
          - name: BUCKET_NAME
            value: "{{workflow.parameters.bucketName}}"

    - name: downloader
      inputs:
        parameters:
          - name: objectName
      container:
        image: "{{workflow.parameters.imageRegistry}}/yardenshoham/local-rebuild-downloader"
        env:
          - name: ENDPOINT
            value: "{{workflow.parameters.endpoint}}"
          - name: ACCESS_KEY
            value: "{{workflow.parameters.accessKey}}"
          - name: SECRET_KEY
            value: "{{workflow.parameters.secretKey}}"
          - name: BUCKET_NAME
            value: "{{workflow.parameters.bucketName}}"
          - name: OBJECT_NAME
            value: "{{inputs.parameters.objectName}}"
      outputs:
        artifacts:
          - name: processor-input
            path: /output/

    - name: processor
      inputs:
        artifacts:
          - name: processor-input
            path: /input/
      container:
        image: "{{workflow.parameters.imageRegistry}}/yardenshoham/glasswall-rebuild-eval:process-mode-0"
      outputs:
        artifacts:
          - name: xml-report
            path: /output/Managed/

    - name: convertor
      inputs:
        artifacts:
          - name: xml-report
            path: /input/
      container:
        image: "{{workflow.parameters.imageRegistry}}/alpine/xml"
        workingDir: /input
        command:
          - sh
          - -c
          - xq .< "$(ls)"
