apiVersion: apps/v1
kind: Deployment
metadata:
  name: input-queue
spec:
  selector:
    matchLabels:
      app: input-queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: input-queue
    spec:
      containers:
      - name: input-queue
        image: minio/minio:RELEASE.2020-05-01T22-19-14Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio1"
        - name: MINIO_SECRET_KEY
          value: "minio1@123"
        ports:
        - containerPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: output-queue
spec:
  selector:
    matchLabels:
      app: output-queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: output-queue
    spec:
      containers:
      - name: output-queue
        image: minio/minio:RELEASE.2020-05-01T22-19-14Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio2"
        - name: MINIO_SECRET_KEY
          value: "minio2@123"
        ports:
        - containerPort: 9000
      