apiVersion: v1
kind: Service
metadata:
  name: input-queue
  labels:
    service: input-queue
spec:
  selector:
    app: input-queue
  ports:
    - name: http
      port:  9000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: output-queue
  labels:
    service: output-queue
spec:
  selector:
    app: output-queue
  ports:
    - name: http
      port:  9000
  type: ClusterIP